
GET http://localhost:5000/api/catFacts


###


POST http://localhost:5000/api/catFacts
Content-Type: application/json

{
    "catName": "Elin"
}


###


PUT http://localhost:5000/api/catFacts
Content-Type: application/json

###


DELETE http://localhost:5000/api/catFacts
Content-Type: application/json

###


