
GET http://localhost:5000/api/catFacts


###


POST http://localhost:5000/api/catFacts
Content-Type: application/json

{
    "catName": "Elin"
}


###

DELETE http://localhost:5000/api/catFacts/catName
Content-Type: application/json

###


